### ISSUE TITLE
[REQUEST] Is it possible to advance also with Lessons?

### ISSUE THREAD

**Issue by rageSpin** [gorouflex/DuoXPy#1]
## Problem
```
session_data = {
        'challengeTypes': [
            'assist',
            'characterIntro',
            'characterMatch',
            'characterPuzzle',
            'characterSelect',
            'characterTrace',
            'completeReverseTranslation',
            'definition',
            'dialogue',
            'form',
            'freeResponse',
            'gapFill',
            'judge',
            'listen',
            'listenComplete',
            'listenMatch',
            'match',
            'name',
            'listenComprehension',
            'listenIsolation',
            'listenTap',
            'partialListen',
            'partialReverseTranslate',
            'readComprehension',
            'select',
            'selectPronunciation',
            'selectTranscription',
            'syllableTap',
            'syllableListenTap',
            'speak',
            'tapCloze',
            'tapClozeTable',
            'tapComplete',
            'tapCompleteTable',
            'tapDescribe',
            'translate',
            'typeCloze',
            'typeClozeTable',
            'typeCompleteTable',
        ],
        'fromLanguage': fromLanguage,
        'isFinalLevel': False,
        'isV2': True,
        'juicy': True,
        'learningLanguage': learningLanguage,
        'skillId': skillId,
        'smartTipsVersion': 2,
        'type': 'SPEAKING_PRACTICE',
    }
```
I tried naively to change _type_ parameter to _LESSON_. Of course no results are obtained.

**Solution**
An interesting solution could be to change the type of Practice/ Lesson to advance also in the learning path.
Is there any API guide where we can understand better what's going in the various requests

**Comment by gorouflex** [comment]
> I tried naively to change _type_ parameter to _LESSON_. Of course no results are obtained.
> 
> **Solution** An interesting solution could be to change the type of Practice/ Lesson to advance also in the learning path. Is there any API guide where we can understand better what's going in the various requests

Duolingo is very restrictive with _LESSON_ or anything that is not _SPEAKING_PRATICE_, I tried it with my alternative account and got instantly banned from Duolingo

**Comment by rageSpin** [comment]
> > I tried naively to change _type_ parameter to _LESSON_. Of course no results are obtained.
> > **Solution** An interesting solution could be to change the type of Practice/ Lesson to advance also in the learning path. Is there any API guide where we can understand better what's going in the various requests
> 
> Duolingo is very restrictive with _LESSON_ or anything that is not _SPEAKING_PRACTICE_, _PRACTICE_, I tried it with my alternative account and got instantly banned from Duolingo

Thanks! I have also tried with another account and no ban at all, but it simply does not work anything

**Comment by gorouflex** [comment]
> > > I tried naively to change _type_ parameter to _LESSON_. Of course no results are obtained.
> 
> > > **Solution** An interesting solution could be to change the type of Practice/ Lesson to advance also in the learning path. Is there any API guide where we can understand better what's going in the various requests
> 
> > 
> 
> > Duolingo is very restrictive with _LESSON_ or anything that is not _SPEAKING_PRACTICE_, _PRACTICE_, I tried it with my alternative account and got instantly banned from Duolingo
> 
> 
> 
> Thanks! I have also tried with another account and no ban at all, but it simply does not work anything

You can try _GLOBAL_PRACTICE_

**Comment by gorouflex** [comment]
I will switch to `GLOBAL_PRACTICE` as it will reduce `skillID` issue
