### ISSUE TITLE
[BUG] Can't get Session Error 500 regardless how many lessons I do

### ISSUE THREAD

**Issue by azur3wrath** [gorouflex/DuoXPy#11]
# Description

Not pasting in the error log as the Action runs smoothly however with the below message:

Starting DuoXPy
Collecting information...
Creating new config folder at: /home/runner/work/DuoXPy/DuoXPy
Date: [20](https://github.com/azur3wrath/DuoXPy/actions/runs/8466137422/job/23194252057#step:3:21)24-03-28
From (Language): en
Learning (Language): ja
**Session Error 500 / No skillId found in xpGains or Missing some element to make a request**
Please do at least 1 or some lessons in your skill tree

The thing is I tried it both on empty, on one lesson done and on almost full lesson step - still getting the same issue.

**Comment by gorouflex** [comment]
@azur3wrath Try another course like Russian or Spanish

**Comment by azur3wrath** [comment]
Works, cheers!

**Comment by gorouflex** [comment]
> Works, cheers!

@azur3wrath, what’s your error course? Since this is a known issue

**Comment by azur3wrath** [comment]
The error one was Japanese, worked on Spanish

**Comment by gorouflex** [comment]
> The error one was Japanese, worked on Spanish

Thanks for your report, will investigate further
