### ISSUE TITLE
[REQUEST] Add updates to DuoXPy.py

### ISSUE THREAD

**Issue by bruh1555** [gorouflex/DuoXPy#3]
**Is your feature request related to a problem? Please describe.**
Yes. I want to add changes to a script to fix the skillId issue.

**How I want you to fix it**
Add a line after 138 and on that new line put the code: skillId = skillId['skillId']

**Comment by bruh1555** [comment]
I hope this is useful to you! Also please add a comment saying you've added this code if you did so I can close this!

**Comment by gorouflex** [comment]
@bruh1555 Please make a PR so I can preview and merge it

**Comment by gorouflex** [comment]
> @bruh1555 Please make a PR so I can preview and merge it

Also, I think the issue with the `skillID` is from my try-except block. I can remove it, and it works fine

**Comment by gorouflex** [comment]
@bruh1555 Fixed in ver 2.0.0
