### ISSUE TITLE
Manual Lesson Trigger Failure [BUG]

### ISSUE THREAD

**Issue by peme969** [gorouflex/DuoXPy#5]
# Debug/Traceback log
![image](https://github.com/gorouflex/DuoXPy/assets/136040410/08e7aef2-ab35-4a17-b9f7-b22c247dc2b6)
I only set the lessons to 2 and i still get the *No skillId found in xpGains* error!
```
Run python main.py
------- Welcome to DuoXPy -------
Made by GFx
Powered by GitHub Actions V3 and Python
Run with GitHub Actions: Yes
Current repo: peme[9](https://github.com/peme969/DuoXPy/actions/runs/7633313224/job/20795274026#step:3:10)69/DuoXPy
Your repo is up-to-date with the original repo
Lessons: 2
Codename: Sandy
Config folder: /home/runner/work/DuoXPy/DuoXPy/Config
---------------------------------
Starting DuoXPy
Collecting information...
Creating new config folder at: /home/runner/work/DuoXPy/DuoXPy
No skillId found in xpGains
Please do at least 1 or 9 lessons
Error: Process completed with exit code 1.
```

I also tried 0 lessons, 1 lesson, 2 lessons etc... but its still not working!

**Comment by gorouflex** [comment]
@peme969 Please read my docs about this error , https://github.com/gorouflex/DuoXPy#how-to-fix-error-500---no-skillid-found-in-xpgains

**Comment by gorouflex** [comment]
@peme969 Since skillID kinda tricky for me, and I'm still investigating more about the skillID, this fix is for only temporary

**Comment by gorouflex** [comment]
@peme969 try latest commit ( sync ur repo ) maybe can fix the skillID error

**Comment by gorouflex** [comment]
Closed, this is common issue, please visit https://github.com/gorouflex/DuoXPy#how-to-fix-error-500---no-skillid-found-in-xpgains for more information

**Comment by peme969** [comment]
I already synced the repo and if you see the logs it is synced

**Comment by gorouflex** [comment]
@peme969 please visit https://github.com/gorouflex/DuoXPy#how-to-fix-error-500---no-skillid-found-in-xpgains to fix this common issue

**Comment by gorouflex** [comment]
@peme969 your repo still not synced yet 
![image](https://github.com/gorouflex/DuoXPy/assets/98001973/96caa3bd-da72-466b-aa9a-cdd05b9a545e)
![image](https://github.com/gorouflex/DuoXPy/assets/98001973/1dd0ecb0-a02e-42ba-b303-56eb6edf9a73)

**Comment by gorouflex** [comment]
![image](https://github.com/gorouflex/DuoXPy/assets/98001973/3e3f8dac-3341-4cb2-94c1-d7b0fdc465b5)

@peme969 How to sync your repository

**Comment by peme969** [comment]
Oh ok! Will do

**Comment by peme969** [comment]
Its fixed now! Thanks for your replies 😁

**Comment by gorouflex** [comment]
> Its fixed now! Thanks for your replies 😁 

You're welcome
