### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by drallap** [gorouflex/DuoXPy#9]
# Debug/Traceback log

```
--------- Traceback log ---------
❌ Error code 4: Failed to fetch commit information
Please refer to: https://github.com/gorouflex/HoneygainPot/blob/main/Docs/Debug.md for more information
Or create an Issue on GitHub if it still doesn't work for you.
Error: Process completed with exit code 255.
```

# Description

**Comment by drallap** [comment]
Daily lessons didnt work for me today, idk why

**Comment by gorouflex** [comment]
@drallap Oh sorry i forgot to set a bypass to this thing, you can re-run this job on GitHub Actions

**Comment by gorouflex** [comment]
@drallap Please sync your repo

**Comment by gorouflex** [comment]
@drallap ![image](https://github.com/gorouflex/DuoXPy/assets/98001973/3f741ded-dd08-4131-afb8-5bfd7acc474d)

**Comment by gorouflex** [comment]
Closed because this issue user fault ( sync your repo )
